### PR TITLE
Enhance deployment command to have support for runtests and dynamic RunRepositoryTests

### PR DESCRIPTION
**Pull request by legetz**
- Added new option `--testlevel RunRepositoryTests` which will dynamically detect all GIT repository test classes and runs the deployment with found tests. This will speed up the validation/deployment on cases where GIT repository module contains subset of all tests found in the org
- Added `--runtests` support in order to pass certain APEX test classes when `--testlevel RunSpecifiedTests` is used

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
Great contribution :)
Selecting test classes is not something I like a lot but... probably there are good reasons to use it on awfully crappy projects :D

**Comment by nvuillam** [comment]
@legetz please can you test with beta version to confirm it's ok before I release ? :)

**Comment by legetz** [comment]
Hey,

Sure, I will test it later today/early monday morning and let you know.

Leo

**Comment by legetz** [comment]
@nvuillam : I tested now latest main branch code. My actual change works okay, it will start `sfdx force:source:deploy` correctly with relevant parameters and also the validation/deployment goes okay from SF side. However it returns error after deployment/validation from the code coverage step which I did not touch.

Here is output example:
`✔ [sfdx-hardis][command] sfdx force:source:deploy -x "/var/folders/bd/d3g05g0102d0qyy7bd_4fk1c0000gn/T/sfdx-hardis-w7gas5/mainPackage.xml" --wait 60 --ignorewarnings --testlevel RunSpecifiedTests --runtests BDC_ConstantsTest --postdestructivechanges ./manifest/destructiveChanges.xml --targetusername leo.jokinen@xxx.com.dev --checkonly --verbose --coverageformatters json-summary
[sfdx-hardis] Deploying v58.0 metadata to leo.jokinen@xxx.com.dev using the v59.0 SOAP API.
Deploy ID: 0Af5E00003AZ13jSAD

=== Deployed Source

 FULL NAME         TYPE      PROJECT PATH
 ───────────────── ───────── ───────────────────────────────────────────────────────────────────────
 BDC_Constants     ApexClass force-app/main/default/classes/BDC/BDC_Constants.cls
 BDC_Constants     ApexClass force-app/main/default/classes/BDC/BDC_Constants.cls-meta.xml
 BDC_ConstantsTest ApexClass force-app/main/default/classes/BDC/tests/BDC_ConstantsTest.cls
 BDC_ConstantsTest ApexClass force-app/main/default/classes/BDC/tests/BDC_ConstantsTest.cls-meta.xml


=== Test Success [1]

 Name              Method
 ───────────────── ─────────────
 BDC_ConstantsTest testConstants

=== Apex Code Coverage

 Name          % Covered Uncovered Lines
 ───────────── ───────── ───────────────
 BDC_Constants 100%      []

Total Test Time:  120

=== Coverage or Junit Result Report Locations

Code Coverage formats, [json-summary], written to 0Af5E00003AZ13jSAD/coverage
Successfully validated the deployment.

ERROR running hardis:project:deploy:sources:dx:  [sfdx-hardis][apextest] Test run coverage (org wide) 100.00% should be > to 75.00%
[sfdx-hardis] hardis:project:deploy:sources:dx execution time 0:01:51.757
`

coverage-summary.json has:
`{
	"total": {
		"lines": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"statements": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"functions": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"branches": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"branchesTrue": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": "Unknown"
		}
	},
	"no-map/BDC_Constants": {
		"lines": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"functions": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"statements": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		},
		"branches": {
			"total": 0,
			"covered": 0,
			"skipped": 0,
			"pct": 100
		}
	}
}`

Most likely SFDX behaves different way for `--coverageformatters json-summary` when `--testlevel RunSpecifiedTests`. Let's debug/test more tomorrow :)

**Comment by legetz** [comment]
@nvuillam : Checked the coverage code bit closer and `extractOrgCoverageFromLog` uses stdout first and secondly coverage output JSON file. stdout do not contain "Org Wide Coverage" in case of RunSpecifiedTests so it parses the JSON file where something goes wrong. I will test this more tomorrow to debug JSON part

**Comment by legetz** [comment]
@nvuillam : Found the bug in `checkDeploymentOrgCoverage`, it was giving false-positive if 100 number was compared to string. Will make another pull-request for that fix now

**Comment by nvuillam** [comment]
@legetz the coverage reports provided by code SF are... a little bit messy indeed ^^
I'm waiting for your PR to release a new version with your PR + Bitbucket & Slack integration ^^

**Pull request merged**
